---
title: Secret Agent Chat
hero_image: images/banner.png
description: Learn how to send unbreakable encrypted messages with Python
original_url: https://raspberrypi.org/learning/secret-agent-chat
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-0, manufacture-0, community-0
interests: cybersecurity-and-cryptography
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
- title: Introduction
- title: What you will need
  completion: engaged
- title: Secret agent chat
- title: Generating a one-time pad
- title: Loading a sheet from the OTP
- title: Writing a secret message
- title: Loading and saving the messages
- title: Encrypting a message
- title: Decrypting messages
- title: Adding a menu
- title: Full code listing
  completion: internal
- title: Using the program
- title: What next?
