---
title: गुप्त जासूस बातचीत(Secret Agent Chat)
hero_image: images/banner.png
description: Python से अटूट एन्क्रिप्टेड (encrypted) संदेश भेजना सीखीए
original_url: https://raspberrypi.org/learning/secret-agent-chat
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-0, manufacture-0, community-0
interests: cybersecurity-and-cryptography
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
- title: परिचय
- title: आपको किन चीजों की आवश्यकता होगी
  completion: engaged
- title: गुप्त जासूस बातचीत
- title: वन-टाइम पैड बनाना
- title: OTP से पत्र लोड करना
- title: गुप्त संदेश लिखना
- title: संदेशों को लोड करना और सहेजना
- title: संदेश एन्क्रिप्ट करना
- title: संदेशों को डिक्रिप्ट करना
- title: मेनू जोड़ना
- title: पूर्ण कोड सूची
  completion: internal
- title: प्रोग्राम का उपयोग करना
- title: आगे क्या?
